### ISSUE TITLE
Getting a better picture of the exporter ecosystem (glTF Exporter Matrix and Checklist)

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/glTF#1271]
Currently we have a number of glTF exporters with partial support for glTF 2.0. It would be great if we could help artists find the right exporter for their pipeline and required features. We'd also like to help developers find the best projects for them to contribute to.

I'm compiling a matrix of exporters and their supported features. I could use the help of the community in building this matrix. I've created an exporter feature checklist for people to fill out and submit in this thread. I'll add it to the matrix and we can update it as these exporters mature. Hopefully, this pushes people to fill in the missing pieces of these exporters and we can enjoy a more robust exporter ecosystem.

Please let me know if there are items that should be added, removed, or changed in this list. My intention is to keep it high level enough that it isn't information overload, but detailed enough that you can find out if the exporter will work for you. Thank you!

# glTF Exporters

| Exporter Name | .gltf/.bin | .glb | Morph Targets | Skinned Mesh | PBR Metallic Roughness | PBR Specular Glossiness (Extension) | Unlit Material (Extension) | Additional Maps | Alpha | Double Sided Materials | Cameras | Animation (TRS) | Animation (Weights) | Draco Mesh Compression (extension) | Custom Extras Data | Asset Info |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [FBX2glTF](https://github.com/facebookincubator/FBX2glTF) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [obj2gltf](https://github.com/AnalyticalGraphicsInc/OBJ2GLTF) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [3DS Max Exporter](http://doc.babylonjs.com/resources/3dsmax_to_gltf) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [Maya2glTF](https://github.com/Ziriax/Maya2glTF) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [Unity-glTF-Exporter](https://github.com/sketchfab/Unity-glTF-Exporter) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [Clay Viewer fbx2gltf](https://github.com/pissang/clay-viewer#converter) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [Sketchup glTF Export](https://extensions.sketchup.com/en/content/gltf-exporter) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [blendergltf](https://github.com/Kupoman/blendergltf) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [assimp](http://www.assimp.org/) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |
| [PiXYZ Studio](https://www.pixyz-software.com/studio/) | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ | ❔ |

### Key:
- ✔️ Full support
- ⚠️ Partial Support
- ❌ No Support
- ❔ Needs Data

# glTF Exporter Checklist
- [ ] JSON Export (.gltf, .bin, .png/.gif/.jpg)
  The exporter can output a .gltf file, a .bin file, and images for each of the textures.
- [ ] Binary Export (.glb)
  The exporter can output a single .glb file containing the glTF JSON data, buffer data, and textures.
- [ ] Morph Targets
  The exporter outputs morph target information via `primitive.targets` and `primitive.weights`. This does not include animation of the weights.
- [ ] Skinned Mesh
  The exporter outputs skins using the `inverseBindMatrices`, `joints`, and`skeleton` properties as well as the `JOINTS` and `WEIGHTS` vertex attributes.
- [ ] PBR Metallic Roughness Material
  The exporter outputs the correct factors and textures for the `pbrMetallicRoughness` material.
- [ ] KHR_matrials_pbrSpecularGlossiness
  The exporter outputs the correct factors and textures for the `pbrSpecularGlossiness` material.
- [ ] KHR_material_unlit
  The exporter supports exporting unlit materials. The material has the correct fallback values.
- [ ] Additional Maps
  The exporter outputs the correct factors and textures for the `normal`, `occulsion`, and `emissive` maps.
- [ ] Alpha Coverage
  The exporter outputs the correct `alphaMode`, `alphaCutoff` and alpha value for the given material.
- [ ] Double Sided Material
  The exporter can specify whether or not the material is double sided and outputs the correct `doubleSided` value.
- [ ] Cameras
  The exporter supports exporting both perspective and orthographic cameras.
- [ ] Animation (TRS)
  The exporter supports exporting animations of the `translation`, `rotation`, and `scale` properties of nodes. This includes joints in skinned meshes.
- [ ] Animation (Weights)
  The exporter supports exporting animation of morph target weights.
- [ ] KHR_draco_mesh_compression
  The exporter supports exporting compressed meshes via the Draco mesh compression library.
- [ ] Extras Data
  The exporter allows you to specify `extras` data on (at minimum) `node` objects.
- [ ] Asset Information
  The exporter outputs the correct glTF `version`, the `generator` name, and allows you to specify the `copyright` field.

# Post template

```
# Exporter Name
- [ ] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [ ] Binary Export (.glb)
- [ ] Morph Targets
- [ ] Skinned Mesh
- [ ] PBR Metallic Roughness Material
- [ ] KHR_matrials_pbrSpecularGlossiness
- [ ] KHR_material_unlit
- [ ] Additional Maps
- [ ] Alpha Coverage
- [ ] Double Sided Material
- [ ] Cameras
- [ ] Animation (TRS)
- [ ] Animation (Weights)
- [ ] KHR_draco_mesh_compression.
- [ ] Extras Data
- [ ] Asset Information
```

If a feature is missing, please try to provide some details. If it has partial or no support please indicate that. Linking to specific Github issues would be even better!

I'll be looking into FBX2glTF and Maya2glTF over the next week.

**Comment by donmccurdy** [comment]
That is a beautiful and ambitious matrix you have there. 😁

Could I request an extra column for multiple animations? Sadly it is painfully missing from nearly all of these.

**Comment by donmccurdy** [comment]
# glTF-Blender-Exporter
- ✔️  JSON Export (.gltf, .bin, .png/.gif/.jpg)
- ✔️  Binary Export (.glb)
- ⚠️ Morph Targets *(generally works well, but a few issues)*
- ⚠️ Skinned Mesh *(certain workflows, e.g. parenting to bones, must be avoided)*
- ✔️ PBR Metallic Roughness Material *(requires custom Cycles node)*
- ✔️ KHR_matrials_pbrSpecularGlossiness *(requires custom Cycles node)*
- ✔️ KHR_material_unlit
- ✔️ Additional Maps
- ✔️ Alpha Coverage
- ❌  Double Sided Material
- ✔️ Cameras
- ✔️ Animation (TRS)
- ✔️ Animation (Weights)
- ❌ KHR_draco_mesh_compression.
- ✔️ Extras Data
- ⚠️ Asset Information

(NOTE: Maintainers please feel free to edit this comment if it needs correction, to keep the comment churn limited.)

**Comment by zellski** [comment]
From memory, this is FBX2glTF, but feel free to edit the borderline cases as you like:

# FBX2glTF
- [✔️] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [✔️] Binary Export (.glb)
- [✔️] Morph Targets (
- [✔️] Skinned Mesh
- [✔️] PBR Metallic Roughness Material
- [❌] KHR_matrials_pbrSpecularGlossiness
  - (support recently removed, as there's no existing natural source of such materials in the FBX world that I know of)
- [✔️] KHR_material_unlit
- [✔️] Additional Maps
- [✔️] Alpha Coverage
  - (only blend/opaque -- not sure FBX materials have this?)
- [❌] Double Sided Material
  - (not sure FBX materials have this?)
- [✔️] Cameras
- [✔️] Animation (TRS)
- [✔️] Animation (Weights)
- [✔️] KHR_draco_mesh_compression.
- [❌] Extras Data
  - (this seems tricky to do in a general way -- why `node` especially?)
- [⚠️] Asset Information
  - (option to set copyright is a great idea, will fix)

**Comment by Kupoman** [comment]
# blendergltf
- :heavy_check_mark: JSON Export (.gltf, .bin, .png/.gif/.jpg)
- :heavy_check_mark: Binary Export (.glb)
- :heavy_check_mark: Morph Targets
- :heavy_check_mark: Skinned Mesh
- :heavy_check_mark: PBR Metallic Roughness Material
- :x: KHR_matrials_pbrSpecularGlossiness
- :x: KHR_material_unlit
- :heavy_check_mark: Additional Maps
- :warning: Alpha Coverage (Alpha values are exported, but `alphaMode` and `alphaCutoff` are not set)
- :x: Double Sided Material
- :heavy_check_mark: Cameras
- :heavy_check_mark: Animation (TRS)
- :heavy_check_mark: Animation (Weights)
- :x: KHR_draco_mesh_compression.
- :heavy_check_mark: Extras Data
- :heavy_check_mark: Asset Information

**Comment by emackey** [comment]
@donmccurdy I updated the doubleSided one to say:

⚠️ Double Sided Material *(requires custom Cycles node, doesn't use Blender's own flag)*

**Comment by robertlong** [comment]
I updated the matrix, added the multiple animations column, and edited the comments.

@donmccurdy and @Kupoman could you fill in the multiple animations item in your checklists? I think it's missing from both of those exporters, but I could be wrong.

@zellski the extras data on node is useful for application specific behavior that doesn't belong in an extension. I think it's hard to do in a general way to all the glTF properties, but node seems like it would be the easiest and most useful.

@donmccurdy I'd rather keep the Draco column. I think it's useful to be able to export an optimized asset directly from an exporter. Not all of them will implement the extension and when they don't users can use the glTF pipeline tool or some Draco compression tool.

**Comment by donmccurdy** [comment]
> @donmccurdy and @Kupoman could you fill in the multiple animations item in your checklists? 

I've updated both — blendergltf supports multple animations, and support is [in progress](https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166) for the Khronos exporter.

> @donmccurdy I'd rather keep the Draco column.

Ok, sounds good.

**Comment by donmccurdy** [comment]
# obj2gltf
- ✔️ JSON Export (.gltf, .bin, .png/.gif/.jpg)
- ✔️ Binary Export (.glb)
- ❌ Morph Targets
- ❌ Skinned Mesh
- ⚠️ PBR Metallic Roughness Material
*OBJ does not have PBR materials, approximate conversion available.*
- ⚠️ KHR_matrials_pbrSpecularGlossiness
*OBJ does not have PBR materials, approximate conversion available.*
- ❌ KHR_material_unlit
- ✔️ Additional Maps
- ✔️ Alpha Coverage
- ❌ Double Sided Material
- ❌ Cameras
- ❌ Animation (TRS)
- ❌ Animation (Weights)
- ❌ Animation (Multiple)
- ❌ KHR_draco_mesh_compression.
- ❌ Extras Data
- ❌ Asset Information

**Comment by pjcozzi** [comment]
Any chance the following folks could chime in on their glTF exporter capabilities?
* @lasalvavida - COLLADA2GLTF
* @Ziriax - Maya2glTF
* @deltakosh - BabylonJS Max glTF exporter
* @bghgary - UnityGlTF
* @pissang - Clay fbx2gltf
* @albn - Sketchfab
* @kimkulling - assimp

Thanks, it is deeply appreciated! 👏

**Comment by deltakosh** [comment]
Sure thing!

**Comment by deltakosh** [comment]
# Ebabylonjs 3dsMax gltf exporter
- [x] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [x] Binary Export (.glb)
- [x] Morph Targets
- [x] Skinned Mesh
- [x] PBR Metallic Roughness Material
- [ ] KHR_matrials_pbrSpecularGlossiness
- [ ] KHR_material_unlit
- [x] Additional Maps
- [ ] Alpha Coverage
- [x] Double Sided Material
- [x] Cameras
- [x] Animation (TRS)
- [x] Animation (Weights)
- [x] Animation (Multiple)
- [ ] KHR_draco_mesh_compression.
- [ ] Extras Data
- [x] Asset Information

**Comment by deltakosh** [comment]
# Babylonjs Maya gltf exporter
- [x] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [x] Binary Export (.glb)
- [ ] Morph Targets
- [ ] Skinned Mesh
- [x] PBR Metallic Roughness Material
- [ ] KHR_matrials_pbrSpecularGlossiness
- [ ] KHR_material_unlit
- [x] Additional Maps
- [ ] Alpha Coverage
- [x] Double Sided Material
- [ ] Cameras
- [ ] Animation (TRS)
- [ ] Animation (Weights)
- [ ] Animation (Multiple)
- [ ] KHR_draco_mesh_compression.
- [ ] Extras Data
- [x] Asset Information

**Comment by pjcozzi** [comment]
Very nice, thank you kindly @deltakosh!

**Comment by Ziriax** [comment]
# Maya2glTF exporter

- Fully supports and exports Khronos PBR shader, ported to Maya GLSL material
- Exports glTF, glb, bin, images
- Merges metallic, roughness, occlusion into a single texture
- Exports meshes
- Handles mirrored UVs (bitangent sign)
- Supports alphaMode
- Multiple TRS animation clips
- Always bakes animation so all Maya constraints can be used
- Reconstructs different hierarchy based on selection
- Can use a MikkTspace for generating tangents
- Converts standard Maya materials to PBR (partially)

Short term (coming weeks)
- blend shapes and animation
- skinning and animation
- adding extra glTF nodes to support Maya’s segment scale compensation 
- support for Trax clips

Long term:
- support for shearing 
- custom Maya blend shape modifier to blend normals

**Comment by donmccurdy** [comment]
Thanks @Ziriax! Would you mind editing to match the template (and then add any notes inline or below that)? 😇

**Comment by robertlong** [comment]
Updated the matrix. Thanks everyone!

**Comment by ziedbha** [comment]
# UnityGLTF
- ⚠️ JSON Export (.gltf, .bin, .png)
- ❌ Binary Export (.glb)
- ❌ Morph Targets
- ❌ Skinned Mesh
- ✔️ PBR Metallic Roughness Material
- ✔️ KHR_matrials_pbrSpecularGlossiness
- ❌ KHR_material_unlit
- ⚠️ Additional Maps
_(normal maps are broken)_
- ✔️ Alpha Coverage
- ✔️ Double Sided Material
- ❌ Cameras
- ❌ Animation (TRS)
- ❌ Animation (Weights)
- ❌ Animation (Multiple)
- ❌ KHR_draco_mesh_compression.
- ❌ Extras Data
- ⚠️ Asset Information
_(no copyright information)_

Looking to fix some bugs with texture exporting and accessor information soon.

**Comment by CentaurMare** [comment]
# Sketchup glTF export
⚠️ JSON Export (.gltf, .bin, .png)
(Creates .gltf embedded, does not write external .bin/.png files) 
✔️ Binary Export (.glb)
❌ Morph Targets
❌ Skinned Mesh
❌ PBR Metallic Roughness Material
❌ KHR_matrials_pbrSpecularGlossiness
❌ KHR_material_unlit
❌ Additional Maps
✔️ Alpha Coverage
✔️ Double Sided Material
❌ Cameras
❌ Animation (TRS)
❌ Animation (Weights)
❌ Animation (Multiple)
❌ KHR_draco_mesh_compression.
❌ Extras Data
❌ Asset Information

Sketchup only supports diffuse materials (textured and non-textured), and doesn't support animations.

**Comment by pjcozzi** [comment]
@lasalvavida or @ziriax any chance you could provide input on COLLADA2GLTF for this capability matrix?

**Comment by lasalvavida** [comment]
Thanks for the reminder @pjcozzi, I'll try to get to this sometime this evening

**Comment by lasalvavida** [comment]
# COLLADA2GLTF
- [x] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [x] Binary Export (.glb)
- [ ] Morph Targets
- [x] Skinned Mesh
- [x] PBR Metallic Roughness Material
- [x] KHR_matrials_pbrSpecularGlossiness
- [x] KHR_material_unlit
- [ ] Additional Maps
- [ ] Alpha Coverage
- [ ] Double Sided Material
- [x] Cameras
- [x] Animation (TRS)
- [ ] Animation (Weights)
- [x] Animation (Multiple)
- [x] KHR_draco_mesh_compression.
- [ ] Extras Data
- [ ] Asset Information

**Comment by donmccurdy** [comment]
Thanks @lasalvavida! One minor thing: I'm taking "Animations (Multiple)" to refer to grouping `<animation_clip/>` nodes into separate glTF animations, per https://github.com/KhronosGroup/COLLADA2GLTF/issues/130. To my understanding COLLADA2GLTF does not support this quite yet.

**Comment by lasalvavida** [comment]
> I'm taking "Animations (Multiple)" to refer to grouping <animation_clip/> nodes into separate glTF animations, per KhronosGroup/COLLADA2GLTF#130. To my understanding COLLADA2GLTF does not support this quite yet.

Makes sense, I'll uncheck it.

**Comment by Ziriax** [comment]
@robertlong I updated the Maya2glTF matrix, the exporter now supports exporting blend-shapes and skinning. Can you update the main matrix please? Thanks!

**Comment by Kupoman** [comment]
Fixed the problems with alpha coverage output in blendergltf. I have updated the status post to reflect these changes.

**Comment by donmccurdy** [comment]
The BabylonJS 3DS Max exporter is listed twice - is that a typo, or is there another tool we'd meant to link to?

**Comment by robertlong** [comment]
Yeah, thanks for catching that. I've removed the duplicate entry.

**Comment by pjcozzi** [comment]
@robertlong perhaps it is worth adding an N/A icon since some tools would never be able to check all the boxes since their input format, e.g., OBJ, doesn't support the features.

**Comment by pjcozzi** [comment]
Does anyone else want to chime in here?

Perhaps
* @sbtron - UnityGlTF
* @kimkulling - assimp

**Comment by lasalvavida** [comment]
Update: double sided materials are supported in COLLADA2GLTF 2.1.1

**Comment by deltakosh** [comment]
Update for Babylon/s maya exporter:
# Babylon.js Maya gltf exporter
- [x] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [x] Binary Export (.glb)
- [x] Morph Targets
- [x] Skinned Mesh
- [x] PBR Metallic Roughness Material
- [ ] KHR_matrials_pbrSpecularGlossiness
- [ ] KHR_material_unlit
- [x] Additional Maps
- [ ] Alpha Coverage
- [ ] Double Sided Material
- [x] Cameras
- [x] Animation (TRS)
- [x] Animation (Weights)
- [ ] Animation (Multiple)
- [ ] KHR_draco_mesh_compression.
- [ ] Extras Data
- [x] Asset Information

**Comment by robertlong** [comment]
Updated, thanks @deltakosh!

**Comment by pjcozzi** [comment]
@robertlong do you think these features should also be part of the table?
* Multiple UV sets
* Mesh instancing , including sharing an instance with different materials

**Comment by robertlong** [comment]
Thanks @pjcozzi, I've updated the matrix to include those columns. I haven't filled them in yet though. I'll need some help from the community.

> including sharing an instance with different materials

How would you define an instance with different materials? I didn't know this was currently possible in glTF 2.0.

**Comment by donmccurdy** [comment]
> How would you define an instance with different materials?

In three.js we try to assume this is the intention when two meshes reference the same accessors but different materials. The spec does not explicitly state any such relationship, and it gets complicated when multiple primitives are considered, but I think it's reasonable to encourage exporters to reuse accessors wherever possible. In any case, loaders should not have to compare vertex data to identify reused meshes.

**Comment by robertlong** [comment]
Thanks, yeah that makes sense. I'll make accessor reuse part of the instanced mesh feature description.

Buffer reuse for vertex attributes is probably another best practice that may belong in here somewhere. Maybe I'll make a separate column for these two features. What do you think?

**Comment by donmccurdy** [comment]
Guessing you mean buffer views, not buffers, but yeah bufferview de-duplication — and generally not creating more bufferviews than necessary — could be reasonable to include here. I think they could be combined in a single column.

**Comment by robertlong** [comment]
Yeah, I meant buffer views. Cool, I'll add the column.

**Comment by alexkowel** [comment]
Hi, thank you for making this list. We at Soft8Soft develop glTF exporters for 3ds Max and Blender.

# Verge3D for 3ds Max
- [x] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [x] Binary Export (.glb)
- [x] Morph Targets
- [x] Skinned Mesh
- [x] Buffer View and Accessor Reuse
- [x] Mesh Instancing
- [x] PBR Metallic Roughness Material
- [ ] KHR_matrials_pbrSpecularGlossiness
- [ ] KHR_material_unlit
- [x] Additional Maps
- [x] Multiple UV Sets
- [x] Alpha Coverage
- [x] Double Sided Material
- [x] Cameras
- [x] Animation (TRS)
- [x] Animation (Weights)
- [x] Animation (Multiple)
- [ ] KHR_draco_mesh_compression.
- [x] Extras Data
- [x] Asset Information

**Comment by alexkowel** [comment]
# Verge3D for Blender
- [x] JSON Export (.gltf, .bin, .png/.gif/.jpg)
- [x] Binary Export (.glb)
- [x] Morph Targets
- [x] Skinned Mesh
- [x] Buffer View and Accessor Reuse
- [x] Mesh Instancing
- [x] PBR Metallic Roughness Material
- [ ] KHR_matrials_pbrSpecularGlossiness
- [ ] KHR_material_unlit
- [x] Additional Maps
- [x] Multiple UV Sets
- [x] Alpha Coverage
- [x] Double Sided Material
- [x] Cameras
- [x] Animation (TRS)
- [x] Animation (Weights)
- [x] Animation (Multiple)
- [ ] KHR_draco_mesh_compression.
- [x] Extras Data
- [x] Asset Information

More info on how to use these exporters can be found [here](https://www.soft8soft.com/docs/).

**Comment by thomlucc** [comment]
### Update for Babylon.js 3ds Max glTF Exporter Checklist:
[✔️] JSON Export (.gltf, .bin, .png/.gif/.jpg)
[✔️] Binary Export (.glb)
[✔️] Morph Targets
[✔️] Skinned Mesh
[✔️] Buffer View and Accessor Reuse
[✔️] Mesh Instancing
[✔️] PBR Metallic Roughness Material
[❌] KHR_matrials_pbrSpecularGlossiness
[❌] KHR_material_unlit
[✔️] Additional Maps
[✔️] Multiple UV Sets (Only supports up to 2 UV sets currently)
[✔️] Alpha Coverage
[⚠️] Double Sided Material (Only supported for 3dsMax Standard materials)
[✔️] Cameras
[✔️] Animation (TRS)
[✔️] Animation (Weights)
[✔️] Animation (Multiple) (Includes support for per-node animation selection)
[❌] KHR_draco_mesh_compression.
[❌] Extras Data
[⚠️] Asset Information (No support for copyright info yet)

### Update for Babylon.js Maya glTF Exporter Checklist:
[✔️] JSON Export (.gltf, .bin, .png/.gif/.jpg)
[✔️] Binary Export (.glb)
[✔️] Morph Targets
[✔️] Skinned Mesh
[✔️] Buffer View and Accessor Reuse
[✔️] Mesh Instancing
[✔️] PBR Metallic Roughness Material
[❌] KHR_matrials_pbrSpecularGlossiness
[❌] KHR_material_unlit
[✔️] Additional Maps
[✔️] Multiple UV Sets (Only supports up to 2 UV sets currently)
[❌] Alpha Coverage
[❌] Double Sided Material
[✔️] Cameras
[✔️] Animation (TRS)
[✔️] Animation (Weights)
[✔️] Animation (Multiple)
[❌] KHR_draco_mesh_compression.
[❌] Extras Data
[⚠️] Asset Information (No support for copyright info)

**Comment by pandaGaume** [comment]
Update for Babylon.js 3ds Max glTF Exporter Checklist:
[✔️] JSON Export (.gltf, .bin, .png/.gif/.jpg)
[✔️] Binary Export (.glb)
[✔️] Morph Targets
[✔️] Skinned Mesh
[✔️] Buffer View and Accessor Reuse
[✔️] Mesh Instancing
[✔️] PBR Metallic Roughness Material
[✔️] KHR_matrials_pbrSpecularGlossiness
[✔️] KHR_material_unlit
[✔️] Additional Maps
[✔️] Multiple UV Sets (Only supports up to 4 UV sets currently)
[✔️] Alpha Coverage
[⚠️] Double Sided Material (Only supported for 3dsMax Standard materials)
[✔️] Cameras
[✔️] Animation (TRS)
[✔️] Animation (Weights)
[✔️] Animation (Multiple) (Includes support for per-node animation selection)
[❌] KHR_draco_mesh_compression.
[❌] Extras Data
[⚠️] Asset Information (No support for copyright info yet)
