### ISSUE TITLE
Major draft 1.0 spec items

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#269]
* [ ] **Render state** - #249, #85, #88
* [ ] **Shader metadata** - #97, #84
* [ ] **Lights** - #93
* [ ] **Cube map** - #266
* [ ] **Profiles** - #267, #236, #15 
* [ ] **Extensions** - #230 and #208 (mesh compression)
* [ ] **Spec itself** - #252, #70

Also pushing for:

* [ ] **Morphs** - #164

There are several other smaller topics for the draft 1.0 spec.  For all of them, see the [1.0 Spec](https://github.com/KhronosGroup/glTF/issues?direction=asc&milestone=1&page=1&sort=updated&state=open) milestone.

**Comment by pjcozzi** [comment]
For a 1.0 MVP, I would now suggest we only need schema updates for the following:

* [ ] **Shader metadata** - #97, #84
* [ ] **Cube map** - #266
* [ ] **Extensions** - #230 and #208 (mesh compression)

There are several other smaller topics for.  For all of them, see the [1.0 Spec](https://github.com/KhronosGroup/glTF/issues?direction=asc&milestone=1&page=1&sort=updated&state=open) milestone.

**Comment by fabrobinet** [comment]
we also need to remove light properties and only keep light specified through technique parameters #93

**Comment by pjcozzi** [comment]
Agreed.  Updated.

**Comment by pjcozzi** [comment]
I've narrowed the draft 1.0 scope down to the following issue labels:

* [1.0](https://github.com/KhronosGroup/glTF/labels/1.0) - mostly just notes for the prose in the spec
* [1.0 extensions](https://github.com/KhronosGroup/glTF/labels/1.0%20extension) - extensions of interest

The major 1.0 discussions we need to move forward are:

* [ ] **Node hierarchy - DAG or tree?** #401
* [ ] **Lights** #93
* [ ] **Shader metadata** #97, #84, and #361

**Comment by pjcozzi** [comment]
Closing this since we are down to a manageable number of issues labeled 1.0.  This is now redundant.
