### ISSUE TITLE
tasks for 0.9

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#321]
- [ ] cube map export https://github.com/KhronosGroup/glTF/issues/266
- [x] quaternion export (`orientation`) https://github.com/KhronosGroup/glTF/issues/144
- [ ] compression spec https://github.com/KhronosGroup/glTF/issues/230
- [ ] handle animation clips  https://github.com/KhronosGroup/glTF/issues/300
- [ ] remove `lights` https://github.com/KhronosGroup/glTF/issues/93

**Comment by pjcozzi** [comment]
Closing as duplicate with https://github.com/KhronosGroup/glTF/issues/269#issuecomment-74564635
