### ISSUE TITLE
Common Materials Extension

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#424]
https://github.com/KhronosGroup/glTF/tree/KHR_materials_common/extensions/Khronos/KHR_materials_common

Comments:
- The JSON examples are inconsistent.  Both `1` and `1.0` are used.  Arrays are sometimes on the same line and sometimes one element per line.
- `index_of_refraction` -> `indexOfRefraction`.  glTF uses camel case for property names.
  - Same for `constant_attenuation`, `linear_attenuation`, `falloff_angle`, and `falloff_exponent`.
- Are we sure `CONSTANT` needs all those properties?  How is each used?
- `FLOAT_VEC4` or `SAMPLER_2D` -> In glTF, what is sampler 2D?  Shouldn't this be a string (texture id)?  We need to precisely define where the texture coordinates come from, e.g., if both `diffuse` and `specular` are texures, do they use the same or different set of texture coordinates?
- `technique` - why does this have a default?  Perhaps it should be required.  We should also make this separate from the table and say the table is for the `values` object.
- `"relective": "texture_envmap"` - glTF does not support cube maps.
- This needs to include the equations.
- This needs to include some discussion on how vertex attributes use semantics to map material inputs, e.g., normals, texture coordinates, etc.

> To-do: Patrick need schema for each of the material types... can you help?

Maybe, but I did to finish the core spec reference doc first.  Will let you know later this week.

**Comment by tparisi** [comment]
Related to #84

**Comment by tparisi** [comment]
@pjcozzi yes to all of the above. did we decide to punt on environment maps? guess i missed the memo.

for these two items, yes but it will take a little time to do these

* This needs to include the equations.
* This needs to include some discussion on how vertex attributes use semantics to map material inputs, e.g., normals, texture coordinates, etc.

**Comment by pjcozzi** [comment]
> did we decide to punt on environment maps?

See #266

**Comment by pjcozzi** [comment]
@tparisi any update here?

**Comment by tfili** [comment]
@tparisi Do we really need a separate transparency value? Shouldn't that just be part of the colors?

**Comment by mlimper** [comment]
thanks, after reading over the draft I would say this is exactly the kind of compact, basic material definition which we have been missing wihin glTF so far... definitely very helpful, thanks a lot for the great work!

**Comment by pjcozzi** [comment]
@mlimper any chance you could implement this soon?  Your feedback would be valuable to help tighten up the spec.

**Comment by mlimper** [comment]
What we would like to implement is a very simple material model to transport colors of the parts - here, the CONSTANT, BLINN, PHONG, and LAMBERT models seems like a perfect match.

I guess it could also be okay to use only PHONG or BLINN instead of using both, and maybe even LAMBERT could be left out, for the sake of simplicity, so that there is only CONSTANT and BLINN, for instance (since LAMBERT is just the diffuse part of PHONG / BLINN).
Otherwise, if there are different models and some have a specular component, maybe that one should not be zero by default (so it makes a difference whether you use LAMBERT or PHONG/BLINN)?

Apart from that, my main question would be how exactly the lights fit in. We'll not want to use them within our system (although that doesn't necessarily mean they shouldn't be there), we'd only transport material information. One obvious possibility could move the lights out of this proposal and put them into a separate extension, but maybe that's too much and it's okay if they are optional.

**Comment by pjcozzi** [comment]
We also need prose for generating shaders with skinning.

**Comment by tparisi** [comment]
@mlimper let's not separate out lights, too complex. Let's instead define that an implementation's use of lights is optional, but if it does use them it needs to implement them correctly (or words to that effect)

**Comment by tparisi** [comment]
@tfili no we want to keep transparency separate.

**Comment by tparisi** [comment]
@pjcozzi @mlimper all requested changes are in except the lighting calculations, that's next. 

Please review the last few commits and LMK. I'm actually wondering about this 'optional lights' issue... it's sort of like cameras in the base glTF. What is a conforming implementation obligated to do? I feel like for both cameras and lights the use of them should be optional, but obviously, if they are used they need to be implemented to spec. Thoughts?

**Comment by tparisi** [comment]
First attempt at lighting calculations are in (see 4126edf) - please review

**Comment by mlimper** [comment]
> What is a conforming implementation obligated to do? I feel like for both cameras and lights the use of them should be optional, but obviously, if they are used they need to be implemented to spec. Thoughts?

Well, to be honest, I guess we would not implement lights from glTF, or at least they would get a very low priority, since we usually integrate data from multiple sources to show everythin in a common context. If we would also import lights with every asset, it would all become a huge mess. So, that would probably mean our implementation would not be 100% spec conformant, I guess...

The conceptual problem here, and also with other things such as Cameras, is probably that glTF tries to be a format for both: Defining a single asset, and defining a complete scene setup. It's a problem of scope, lights and cameras often have a global scope, I guess, while meshes can be perfectly seen as something that can be integrated into an existing scene. However, it might not even be that clear for all cases: if a light is supposed to model the sun, it makes sense to ignore it when integrating an asset into an existing scene. In contrast, if a light is supposed to model one of the headlights of a car, attached to the model, it makes probably sense to load it, even if the current context already has lighting.

@pjcozzi What is your approach in Cesium? What would happen if I would try to import an asset that has lights into an existing world?

Possible conclusion: Some frameworks might want to ignore lights that have a global scope. Probably, all frameworks should be able to load lights that have a local scope, if they want to be spec-conformant. Therefore, one could add this scoping property to lights, to separate what is "scene data" and what is "asset data"... (maybe this also makes sense for other properties, such as camera viewpoints?)

Another thing that could make sense is that the glTF spec provides a list of all existing features, such as "meshes", "lights", "cameras", ... . An implementation can then provide a list of features it supports. On top of that, one could identify certain feature sets as "support level X" or "profile Y", to ease communication about the state of an implementation.

**Comment by tfili** [comment]
@tparisi Looking at `technique.parameters` shouldn't the node property be moved into an `extension` object. It looks like it was removed from the core spec, but I don't see it in the extension spec.

**Comment by tparisi** [comment]
@tfili good catch. Please make sure the converter does this and I will update the extension spec.

**Comment by tfili** [comment]
@tparisi @pjcozzi In the converter generated shaders we look in the collada extra tags for double sided lighting and we respect that. It's used by a bunch exporters. Do we want to add this in the extension spec so we can generate the correct shaders or should I output it in the extras tag of the extension?

**Comment by tparisi** [comment]
I personally think we should just put double-sided into the `values`. Extras is just another added level of nonsense. @pjcozzi  what do you think?

**Comment by tfili** [comment]
I agree. Also one issue I'm running into is knowing if an image has transparency. When I get the glTF it just has the extension, so I have to generate techniques/shaders/etc, but I can't correctly detect the states at that point. I would have to wait for the image to load and figure it out. That is very difficult with our workflow. The converter however knows this already, so adding a property there would be much easier. For values that take a color or string, maybe have that be an color or object instead like this
```
"diffuse" : {
    "texture": "texture1",
    "transparent": true
}
```

**Comment by pjcozzi** [comment]
> I personally think we should just put double-sided into the values. Extras is just another added level of nonsense. @pjcozzi what do you think?

OK.

**Comment by pjcozzi** [comment]
As for if lights should be required, I suggest that we allow an asset to not have any lights, in which case, the engine is free to use their own lights, e.g., in Cesium, it would be the sun.  If an asset contains lights, then the engine is required to generate a shader that uses those lights and any engine-specific lights it has.  The Cesium team can make an open-source library to generate the shaders based on @tfili's work.

In the short-term, lights in an asset are not a big deal for Cesium; longer term, we would use them for lights on satellites, aircrafts, trucks, etc.

@tfili what do you think based on your experience implementing this extension so far?

**Comment by pjcozzi** [comment]
The intro says "BLINN" means "Blinn-Phong" but the Blinn section says it means "Blinn-Torrance-Sparrow."  Which is it?  Why not just stock Blinn-Phong?  @tfili is looking at Three, Babylon, etc. to see what they implement, e.g., they might need to implement another a new material if glTF uses Blinn-Torrance-Sparrow and their engine doesn't.

**Comment by pjcozzi** [comment]
More feedback:
* Rename `constant_attenuation` and `linear_attenuation` to `constantAattenuation` and `linearAttenuation`
* `"relective": "texture_envmap"` - glTF does not support cube maps.
* There are properties in the material table that are not used in the equations for any lighting model.  I think this is because they are copied from COLLADA which has a more complicated lighting model.  I suggest removing anything outside of the standard equations you provided.

I can help with the schema, but it will be a bit before I will have the time.

**Comment by tparisi** [comment]
Guys apologies on all the blinn-phong confusion. I cribbed language from COLLADA spec. Can someone suggest a path forward to resolve that?

@pjcozzi I will do the renames... and double-check the list of properties.

**Comment by pjcozzi** [comment]
I would stick just with the Blinn-Phong lighting model as you described in the equation and then remove the unused parameters from the table.

**Comment by tparisi** [comment]
Updated camel case in f594fc7... I'm stuck on this environment map thing, I know we're going to need them before long... @pjcozzi  is there a holdup somewhere in the base spec regarding specifying cube- and sphere-map textures? 

Regarding the lighting calculations and unused params, can you give me an example? I see that some spotlight values aren't taken into account but is there anything else? I believe this is a shortcoming of the equations I cribbed from the COLLADA spec...

**Comment by pjcozzi** [comment]
> @pjcozzi is there a holdup somewhere in the base spec regarding specifying cube- and sphere-map textures?

They are not in the spec.  Time is too tight to put them into 1.0.  See #266.

> Regarding the lighting calculations and unused params, can you give me an example?

The following parameters are not used in the lighting equations for any of the lighting models:
* indexOfRefraction
* reflective
* reflectivity

**Comment by tparisi** [comment]
r/e env maps - check.

r/e those 3 properties - roger that. nuking.

**Comment by tparisi** [comment]
Cleanup done, see 83161f7. Let me look at Blinn-Phong mess.

**Comment by tparisi** [comment]
Cleaned up Blinn-Phong in the intro see aef9485, sorry that was old stuff. I think it's consistent now please review @pjcozzi

**Comment by tfili** [comment]
@tparisi It looks like you missed a few columns in the materials property table.

**Comment by tfili** [comment]
@tparisi Any thoughts on specifying transparency if you are using a texture?

**Comment by tparisi** [comment]
Good catch fixed 76afd19 

Not sure what you mean about transparency using a texture...

**Comment by tfili** [comment]
When implementing this extension I need to figure out whether a material has transparency so I can enable blending. It's easy without textures. With textures, loading all the images to check for transparent images before I process the model is very inconvenient.

**Comment by pjcozzi** [comment]
@tparisi the table of material parameters also needs to define the minimum and maximum value, e.g., see https://github.com/KhronosGroup/glTF/commit/4126edfeb13be38cff013c36dad473a2a286d654#commitcomment-13734984

**Comment by pjcozzi** [comment]
> When the value of technique is BLINN, this defines a material shaded according to the Blinn-Torrance-Sparrow lighting model or a close approximation.

This should be "Blinn-Phong, not "Blinn-Torrance-Sparrow", right?

**Comment by pjcozzi** [comment]
I'm just not sold on the entire intro to the Blinn section.  I find it unlikely that the typical WebGL engine implements Blinn-Torrance-Sparrow nor do I think the extension spec as currently written provides all the parameters for this lighting model.

Instead, we should use a stock Blinn-Phong like:
* Three.js - https://github.com/mrdoob/three.js/blob/master/src/materials/MeshPhongMaterial.js
* BabylonJS - https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/babylon.standardMaterial.ts

**Comment by pjcozzi** [comment]
@tparisi I think we should also explicitly list the attribute input to the material (which is a subset of the parameters) just like stock glTF techniques.  Otherwise, our implementation has to search all the meshes/primitives for the attribute inputs.  See https://github.com/AnalyticalGraphicsInc/cesium/pull/3039/files#r42259749

**Comment by tfili** [comment]
@tparisi We were looking at our implementation and it is annoying to determine the type of the values. I have to do something like this which is probably slower than it needs to be
```javascript
var type = typeof value;
typeValue = -1;
switch (type) {
    case 'string':
        typeValue = WebGLConstants.SAMPLER_2D;
        break;
    case 'number':
        typeValue = WebGLConstants.FLOAT;
        break;
    default:
        if (Array.isArray(value)) {
            // 35664 (vec2), 35665 (vec3), 35666 (vec4)
            typeValue = 35662 + value.length;
        }
        break;
}  
```

My thought was to expand on the idea I had of making it an object for textures and always make it an object with a type like this. `type` and `value` would be required and `transparent` would be for textures only, optional and defaulting to `false`.
```json
"diffuse" : {
    "value": "texture1",
    "type": 35678,
    "transparent": true
}
"specular" : {
    "value": [0.2, 0.2, 0.2, 1.0],
    "type": 35666
}
```

**Comment by pjcozzi** [comment]
+1 for @tfili's suggestion.  We could generalize `"texcoord": "TEXCOORD_0"`  to `"attribute" : "attribute-id"` to also account for https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148762276

**Comment by pjcozzi** [comment]
@tparisi I made a new empty branch from `spec-1.0`: [KHR_materials_common](https://github.com/KhronosGroup/glTF/tree/KHR_materials_common).  Can you please move this extension to that branch so we can cleanly merge `spec-1.0` into master without this work-in-progress?

**Comment by tparisi** [comment]
will do - I'll get that out of the way soon and then we will get back to the list of oustanding issues

**Comment by tfili** [comment]
@tparisi Looking at the light properties, they seem a little weird. Generally lights have a `constantAttenuation`, `linearAttenuation` & `quadraticAttenuation`. This is how COLLADA them defined for common materials as well.

The spec is missing `quadraticAttenuation` and has a `distance` property. I'm not actually sure what to do with the `distance` property. I think we should have it the same way as it was in COLLADA, since that is such a well known technique for defining lights.

**Comment by tparisi** [comment]
sure makes sense adding to the list

**Comment by tfili** [comment]
@tparisi It also looks like we don't need `direction` either as direction and position are controlled by the node the light is attached to.

**Comment by tparisi** [comment]
not true; only position is controlled by the node the light is attached to. there is no `direction` property for a node.

**Comment by tfili** [comment]
Looking at the COLLADA spec it says lights point (0,0,-1) and the rotation of the node orients the light accordingly. Looking at the code in the gltf converter, this was how they were designed in the beginning as well.

Not saying it's correct, but that is how the code currently works.

**Comment by pjcozzi** [comment]
I agree with @tfili that the light should have a well-known direction; otherwise, it is redundant to have have the transform in the node and the direction in the light, e.g., there are two rotations when only one is needed.

**Comment by tparisi** [comment]
I suppose this is ok, we can go with it. Will remove direction.

**Comment by tparisi** [comment]
Removed `direction` and added language defining direction vector. Also added quadraticAttenuation. 8b07ba1

**Comment by tfili** [comment]
@tparisi Also, I also don't think we need `distance`. That is the point of attenuation. You get the distance from the fragment to the light and using the attenuation values you compute the light's contribution to the scene.

**Comment by tparisi** [comment]
Indeed. I just forgot to remove it. On it;

**Comment by tparisi** [comment]
Fixed `distance` and added some language describing how direction and position are calculated (or ignored) per- light type.  b03b4b8

**Comment by pjcozzi** [comment]
I think we have the following issues left to finalize this extension:

* [ ] Clean up Blinn section - https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148722225
* [ ] Expand parameter values - https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148774205
* [ ] List attributes (could be part of the above) - https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148762276

@tparisi @tfili can you confirm

**Comment by tparisi** [comment]
confirmed, hope to get to this today

**Comment by pjcozzi** [comment]
@tparisi any movement here?  We want to finalize our implementation (both COLLADA2GLTF and Cesium).

**Comment by tparisi** [comment]
@pjcozzi Need some input:

*[] I think we should just remove Blinn and have Phong (which is typically implement Blinn-Phong anyway), Lambert and Constant.

*[] I have no idea what you want with these other two issues, you're going to have to explain them to me via voice...

**Comment by tparisi** [comment]
@pjcozzi ok taking another look at Blinn and clearing up the language.

**Comment by tparisi** [comment]
@pjcozzi Simplified Blinn language, I think this is right. 12910f7

**Comment by pjcozzi** [comment]
> @pjcozzi Simplified Blinn language, I think this is right. 12910f7

This is perfect!

**Comment by tparisi** [comment]
@pjcozzi Great. Checked that one off the list.

On to the final two issues. I'm still not convinced. Please pow-wow with @tfili

**Comment by pjcozzi** [comment]
> * [ ] Expand parameter values - https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148774205

I still agree with this.  For example, this:
```javascript
 "KHR_materials_common" : {
  "technique" : "PHONG",
  "values": {
    "diffuse": [ 1, 1, 0, 1]
  }
}
```
would become:
```javascript
 "KHR_materials_common" : {
  "technique" : "PHONG",
  "values": {
    "diffuse": {
      "value": [ 1, 1, 0, 1],
      "type": 35666 // FLOAT_VEC4
    }
  }
}
```
This avoids the implicit type checks in the [code example above](https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148774205), which we do not rely on anywhere else in glTF (everything has an explicit `type`).  I'm surprised you haven't ran into this in Three.js.  For example, how does the code know the difference between a constant diffuse value and a diffuse texture?


I would also consider renaming `values` to `parameters` since this has much better symmetry with techniques than materials, which is OK.  The older `details` approach still had a `technique` - now we do not.

**Comment by pjcozzi** [comment]
@tfili for this one:

>  List attributes (could be part of the above) - #424 (comment)

Instead of explicitly listing the attributes as I suggested or searching the meshes/primitives as our implementation does now, could the extension spec specify that:

* `CONSTANT` lighting requires only `POSITION` attributes.
* `LAMBERT`, `BLINN`, and `PHONG` require `POSITION` and `NORMAL` attributes.

In any case where a parameter is a string (e.g., a texture), then `TEXCOORD_0` attribute is also required.  Note that this could even happen for `CONSTANT` since `emission` can be a texture.

Given this (and ignoring skinning), couldn't the shaders be generated?

As for skinning, perhaps we could add a `jointCount` property to the material, which is zero for no skinning, and non-zero with skinning?

**Comment by tparisi** [comment]
@pjcozzi Adding a type sounds reasonable and it's not too onerous... but I still disagree in principle. If an implementation supports this extension, it should know what types to expect for each values and it should have built-in shaders to handle it.

Disagree about renaming `values`, those are values they're not parameter descriptions. We have `values` when techniques are instanced in the material, so the current proposal is symmetric to that.

I'm OK with the language about attributes.

Why do you need a jointCount?

**Comment by pjcozzi** [comment]
> it should know what types to expect for each values and it should have built-in shaders to handle it.

Yes, but it needs to know the type.  The current approach is clunky, look at the code: https://github.com/KhronosGroup/glTF/issues/424#issuecomment-148774205

> I'm OK with the language about attributes.

OK, let's wait for @tfili to confirm that it will work.

> Why do you need a jointCount?

So the vertex shader can declare the maximum size of the attribute array.

**Comment by tparisi** [comment]
I don't think having to do a typeof check is that big of a deal.

For the `transparent` idea, why not just have a `transparent` boolean on the material itself rather than a property of the texture? This would be separate from the `transparency` value, just a flag that indicates to the engine to turn on alpha blending and alpha-sort the object.

**Comment by pjcozzi** [comment]
> I don't think having to do a typeof check is that big of a deal.

As I said above, it is not consistent with the rest of glTF - and is, well, a bit hacky.

> For the transparent idea, why not just have a transparent boolean on the material itself rather than a property of the texture?

Might be OK.  @tfili would this work?

**Comment by tfili** [comment]
@pjcozzi @tparisi Actually that may be better, since I don't care what texture has transparency, I just need to set the blend state correctly.

**Comment by tparisi** [comment]
@tfili right and that's what you see in a lot of engines, a `transparent` flag on the material itself. very simple so let's do that. It's separate from the `transparency` flag which is the actual value to multiply the alpha by when you have RGB's.

@pjcozzi agreed, hacky. but balance this against verbosity of the JSON. that being said your latest https://github.com/KhronosGroup/glTF/issues/424#issuecomment-150708983 is a pretty concise way to do it.

**Comment by pjcozzi** [comment]
> @tfili right and that's what you see in a lot of engines, a transparent flag on the material itself. 

Let's do it.

> @pjcozzi agreed, hacky. but balance this against verbosity of the JSON. that being said your latest #424 (comment) is a pretty concise way to do it.

I agree it is reasonable.  I suggest we do it and then I think we are good to go with this extension (other than finishing our implementations and the schema).

**Comment by tparisi** [comment]
@pjcozzi OK you won me over. I'll start implementing when @tfili  gives the go-ahead on converter and converted content.

**Comment by tfili** [comment]
Ok, that works for me. I'm working on the implementation now.

**Comment by tfili** [comment]
I've finished the converter and Cesium implementations. The things that should be updated in the spec are:
* Added `doubleSided` to the material (this was discussed and implemented before but never put in the spec).
* Added `transparent` to the material.
* Made all values an object with the properties `type` & `value`

@tparisi @pjcozzi Is there anything else?

**Comment by pjcozzi** [comment]
Nothing else from me.

**Comment by tparisi** [comment]
Hi @tfili good catches. 

Do you or @pjcozzi definitively know the render states that go with both of these flags? If so I'll also add that language. Pretty sure it's `CULL_FACE` disabled for doubleSided, what about for transparency? I imagine it's a combo, please advise on spec language...

**Comment by pjcozzi** [comment]
@tparisi see @tfili maps these to render states here: https://github.com/AnalyticalGraphicsInc/cesium/pull/3039/files#diff-8fd2167b1c1a0711731254f9aa4b45c9R532

**Comment by tparisi** [comment]
@tfili @pjcozzi LMK when we have the models converted and I'll start on the Three.js loader. Are we doing it in master or the materials branch?

**Comment by pjcozzi** [comment]
OK, we'll open a pull request into master with the models.  The issue is #448.

**Comment by tparisi** [comment]
I think the PR should be off the materials branch and then we'll merge back into master once everything is sorted out with the Three.js importer

**Comment by pjcozzi** [comment]
OK, we'll target the pull request to the materials branch.

**Comment by tfili** [comment]
PR in #468

**Comment by tparisi** [comment]
Just checked in language for `doubleSided` and `transparent` please review @pjcozzi

**Comment by pjcozzi** [comment]
`transparency` update looks good.  `doubleSided` needs to mention to flip the normal for backfacing triangles.  For example, here is @tfili's implementation: 
```javascript
            if (khrMaterialsCommon.doubleSided) {
                fragmentShader += '  if (gl_FrontFacing == false)\n';
                fragmentShader += '  {\n';
                fragmentShader += '    normal = -normal;\n';
                fragmentShader += '  }\n';
            }
```

**Comment by pjcozzi** [comment]
To finish this, I believe there are the following outstanding issues:
* [ ] Remove `type`, #523 
   * [ ] Update extension spec
   * [ ] Update COLLADA2GLTF
* [ ] Specular exponent update, #510
* [ ] Add schema to spec
* [ ] Semantics/names, #509 

@tparisi @tfili @mlimper is there anything else?

**Comment by mlimper** [comment]
I think that's it

**Comment by tparisi** [comment]
We can close #510 and #509 - but #523 are we sure about removing type? see
my comment

On Tue, Jan 12, 2016 at 1:36 AM, Max Limper <notifications@github.com>
wrote:

> I think that's it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/glTF/issues/424#issuecomment-170851864>.
>



-- 


Tony Parisi                             tparisi@gmail.com
Follow me on Twitter!             http://twitter.com/auradeluxe
Read my blog at                     http://www.tonyparisi.com/
Learn WebGL                         http://learningwebgl.com/
Mobile                                    415.902.8002
Skype                                     auradeluxe

Read my books!
*Learning Virtual Reality*
http://www.amazon.com/Learning-Virtual-Reality-Experiences-Applications/dp/1491922834


*Programming 3D Applications in HTML5 and
WebGLhttp://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966
<http://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966>WebGL,
Up and Running*
http://www.amazon.com/dp/144932357X

**Comment by mlimper** [comment]
If it would be updated in the examples, it would facilitate implementation and increase compatibility
(Basically, we are staying with your initial proposal https://github.com/KhronosGroup/glTF/issues/424#issuecomment-150713235)

**Comment by pjcozzi** [comment]
We are going to update the samples, see https://github.com/KhronosGroup/glTF/issues/523#issuecomment-171015245

**Comment by yyc-git** [comment]
Hello! Is KHR_materials_common support normal map? I don't see the field in the extension spec.

**Comment by tfili** [comment]
It doesn't. It's meant to mimic Collada's common profile that supports basic lighting models (constant, lambert, blinn and phong). For more advanced techniques you'll have to provide shaders.

**Comment by yyc-git** [comment]
Thanks for your reply.

> For more advanced techniques you'll have to provide shaders.
provide shaders? You mean that I should use the shader generated by gltf converter? Or How can I provide shader?

In my case, I just want to use my shader generated by my engine instead of using the shader provided by gltf converter. My shader supports normal map. 
So How can I read normap map data from .gltf file? Could you give me some suggestions? Thanks.

**Comment by tparisi** [comment]
Hi YYC

You will need to create your own extension. Info here:

https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md

Yours would be a "vendor extension."

I can envision that we would someday add normal maps to the common materials extension. So maybe you can think about designing your extension for eventual inclusion a future version of the KHR_ extension. We can't make about promises about that right now, but please keep the idea in mind while you are designing your feature and let's talk about it soon...

**Comment by yyc-git** [comment]
OK, I get it, thanks a lot~

**Comment by pjcozzi** [comment]
@McNopper OK to close as duplicate with #947 and #945?

**Comment by pjcozzi** [comment]
I believe this it is OK to close this as now duplicate with #1163 and friends.

@donmccurdy please let me know if you think otherwise.
