### ISSUE TITLE
glTF 1.1 will be 2.0!

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#817]
We started glTF 1.1 as a bug fix update to glTF 1.0.  In parallel, @lexaknyazev developed the [glTF Validator](https://github.com/KhronosGroup/glTF-Validator), which helped find corner cases that the 1.1 spec has tightened up.

Also in parallel, something big happened: @mlimper and a large community have nearly finalized the [glTF PBR extension](https://github.com/KhronosGroup/glTF/pull/643).  We have also [decided](https://github.com/KhronosGroup/glTF/issues/696#issuecomment-271880604) that the metallic-roughness PBR material model will be in the core glTF spec (specular-glossiness will remain in the extension).  There is so much spec and implementation progress here that we do not want to hold it back, so PBR will be part of the next glTF version, now named **2.0** to signify the huge advancement with PBR.  We believe PBR in glTF will help the industry move to PBR given the carefully defined spec and emerging ecosystem of tools, runtimes, and sample code.

In addition, we want glTF 2.0 to be a stable base for the future and to support practical runtime implementations for many graphics APIs, so we are including a few other changes to improve consistency, API-neutrality, or performance.  These are:
* [x] Moving GLSL to an extension since API-neutral PBR will be in the core spec. #733
* [x] Adding `image.bufferView` so that textures/geometry/keyframes can be stored in one binary blob if desired, and that the [KHR_binary_glTF](https://github.com/KhronosGroup/glTF/blob/master/extensions/Khronos/KHR_binary_glTF/README.md) extension can be replaced with core glTF spec.  `image.uri` will still be supported.
* [ ] Moving lights in the KHR_common_materials extension to a separate light extension that can be used by both PBR and common_materials.  Engines can, of course, use their own lights as well.
* [x] Replacing top-level glTF object properties that are currently accessed by property name, e.g., the `accessors` object, with arrays that are accessed by index.  This allows faster parsing in JavaScript and native loaders.  We'll post performance numbers in this repo soon. #831
* [x] Adding morph targets, e.g., for facial animation. This is not a breaking change. #210, #820

It is exciting to see the industry move forward together with this next version of glTF.  @cx20 is [tracking the progress](https://github.com/cx20/gltf-test) of several engine adoptions: [three.js](https://github.com/mrdoob/three.js/), [Babylon.js](https://github.com/BabylonJS/Babylon.js), and [GLBoost](https://github.com/emadurandal/GLBoost).  Updates to [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/compare/master...lasalvavida:converter1.1), [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/191), and [Cesium](https://github.com/AnalyticalGraphicsInc/cesium/pull/4808) are also imminent. @javagl has also prepared a [glTF tutorial series](https://github.com/KhronosGroup/glTF-Tutorials/pull/1) including [simple sample models](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.1/README.md).

There's lots of implementation work towards glTF PBR: the [WebGL reference implementation](https://github.com/moneimne/WebGL-PBR/issues/1) by @moneimne, [Babylon.js](https://github.com/KhronosGroup/glTF/issues/697#issuecomment-267453898) by @bghgary and @sbtron, [x3dom](https://github.com/x3dom/x3dom) by @mlimper, [OSGJS/Sketchfab](https://github.com/KhronosGroup/glTF/issues/697#issuecomment-268819087) by @cedricpinson, and the [Laugh Engine](https://github.com/jian-ru/laugh_engine#gltf-support) (Vulkan) by @jian-ru.

Next up, we'll make the 1.1 to 2.0 renames and prepare the spec for Khronos ratification.  As always, please provide your feedback and let us know what you are building with glTF!

**Comment by pjcozzi** [comment]
Also, here's the:
* Overview of spec changes made so far, #605
* Draft spec, #784

**Comment by xelatihy** [comment]
Very exciting work!

Are these schemas already available for the new glTF 2.0 (and extensions)?

**Comment by pjcozzi** [comment]
Things are nearly complete.  The spec is in #784.  The PBR extension is in #643 (note that basically the metallic-roughness section will be cut-and-pasted into the core spec).

**Comment by xelatihy** [comment]
Sounds good. I have manu large models in glTF 1.1 (I guess 2.0). I will publish them soon on my site and plan ti publish more models in the coming months. Adding PBR next.

**Comment by pjcozzi** [comment]
@xelatihy sounds great. When ready, we would be happy to add a link to your models from here: https://github.com/KhronosGroup/glTF-Sample-Models#other-gltf-sample-models.  Please open a pull request.

**Comment by cx20** [comment]
@pjcozzi Does renaming from glTF 1.1 to 2.0 mean that 1.1 is missing?

Do the following samples also change from 1.1 to 2.0?
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.1

**Comment by pjcozzi** [comment]
@cx20 yes, everything will change to 2.0: the spec, the sample models, tools, tutorials, etc.  So there will be just glTF 1.0 and glTF 2.0, not 1.1.

**Comment by cx20** [comment]
@pjcozzi  thanks, I understand.

**Comment by lexaknyazev** [comment]
First 2.0 draft #826.

**Comment by pjcozzi** [comment]
@lexaknyazev can you please check the boxes in the tasklist at the top of this issue if they are already included in #826?  I checked the ones I know for sure.

**Comment by javagl** [comment]
How will the extensions be updated? E.g. for `KHR_binary_glTF`:

> Binary glTF introduces a buffer with id equal to `"binary_glTF"`

Will there be a `KHR_binary_glTF_2` where the buffer is e.g. defined to have an *index* (and maybe always have index `0`)?

Will the removal of lights from `KHR_materials_common` be handled by creating a (**new!**)  `KHR_materials` and a new `KHR_lights`?

**Comment by lexaknyazev** [comment]
@javagl 
> Will there be a `KHR_binary_glTF_2` where the buffer is e.g. defined to have an *index* (and maybe always have index `0`)?

See #828 

> Will the removal of lights from `KHR_materials_common` be handled by creating a (**new!**)  `KHR_materials` and a new `KHR_lights`?

`KHR_materials_common` hasn't been ratified yet, so it will be updated to don't include lights.
They will go to a new `KHR_lights`. I'll push drafts soon.

**Comment by cx20** [comment]
I have created a branch to test the glTF 2.0 models.
https://github.com/cx20/gltf-test/tree/2.0

**Comment by pjcozzi** [comment]
Very nice, thanks @cx20.  We will soon see those red x's turn to green checkboxes!

**Comment by javagl** [comment]
Not sure whether it fits here, but there's another API appearing at the horizon: https://www.w3.org/community/blog/2017/02/07/proposed-group-gpu-for-the-web-community-group/ ( https://webkit.org/wp-content/uploads/webgpu-api-proposal.html ). Something to have an eye on for glTF 3.0 ;-)

**Comment by pjcozzi** [comment]
Closing, no action here.
